### ISSUE TITLE
international version

### ISSUE THREAD

**Issue by ghost** [Sentilix/thaliz-classic#11]
The current code is only for the english game client, because the spells are referenced by the english name.

With this patch the spells are referenced by their spell ID. This should work with any game language.

[diff.txt](https://github.com/Sentilix/thaliz-classic/files/7359476/diff.txt)
.

**Comment by Sentilix** [comment]
Thanks for your contribution.

I have taken your idea and modified it slightly, so instead of translating on-the-fly I added a new val[4] column with the spellIDs. During startup I then translate the spellnames and update the val[3] column.

I do not have an international client I can test this in, so I would be gratefull if you could check this.

**Comment by ArisiaClassic** [comment]
I just tested your new version with the german game client, and it works.

would be nice, if you can release a new version and push that version thru Curse within the next hours. Our raid starts in 7 hours... Thank you for your work.
